### ISSUE TITLE
occasional buffering

### ISSUE THREAD

**Issue by S0und** [Globidev/twitch-player#29]
Maybe it's my connection, but now every 5-10 min there is a buffering, during this time the network drops. But if i watch Twitch on my TV, there is no interruption. This issue happens both on my desktop and my laptop. Previously everything worked fine, this issue appeared in the past 5 days?! 

Maybe twitch changed something which affecting twitchd? I'm on 1.4.7 btw. 

![image](https://user-images.githubusercontent.com/1266308/66516568-9a5f7880-eae1-11e9-909e-bdbdf70c1f59.png)

**Comment by Globidev** [comment]
Hi
The drops you're seeing seem to be caused by "stitched" ads. The player is actually getting advertising video segments, willingly ignoring them and waiting on normal stream segments before resuming the playback. It can take a few seconds and it's indeed annoying.
My guess is that with their recent API changes, they also tweaked some parameters regarding stream playlists and `twitchd` might be sending imperfect requests which cause the playlist to yield ads every ~10 minutes.
I'll have to do some more reverse engineering to see how I can fix this.
In the meantime you could try to add an artificial delay through the `--network-caching` flag of `libvlc`
I'll still try to fix this fast, since it's indeed a big annoyance

**Comment by Globidev** [comment]
Turns out it wasn't due to ads but to a new entry in the video playlist.
Fix deployed in `1.4.8`
